import { createHash } from "node:crypto";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { basename, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const modelDir = resolve(root, "model");
const errors = [];

// Binary models and vendored runtime files cannot be regenerated by the normal
// shader checks. Pin their reviewed bytes so a package never silently substitutes
// a different model/runtime while retaining the same provenance record.
const pinnedArtifacts = {
  "model/rife.onnx": "6a31074c0f588648982b5e828aee6c27e005015a712a46ea63da48c65fa9a26b",
  "model/rife_v4.26.onnx": "af25762dfec02a4bbb949decea63988b01fa56c46c0ff9dc66ac8e2f12cbb661",
  "model/rife_v4.26_fp16.onnx": "65494496be256b2809b6760f87a941c0d80bbc5cb09de0f3f6795488ae1fcd9d",
  "model/neural/span2x_smoke.fp16.onnx": "ae7642c2b3bdd96e475dfcbf6a9180d8ec41175a1329d9f9b2a402f186c05c25",
  "vendor/ort/ort.webgpu.min.mjs": "46988a5a025f49449850f39f95eb0d21e40e67b3beb13a0b54efd3ab5d83f60e",
  "vendor/ort/ort-wasm-simd-threaded.asyncify.mjs": "7236653b8565da4046e459cd0e274123419a1d9f1f8f18fd36c28058346ca655",
  "vendor/ort/ort-wasm-simd-threaded.asyncify.wasm": "7e83cd6cee77e478bc96a7e91b198144fb5e4126287daf1f9b54bb195ebcd55a",
  "shaders/upstream/FSRCNNX_x2_16-0-4-1.glsl": "d5a24a271e5d9a3f7f7a053b150c460a44c25b3cf7f770857d57cc3a2e1c9965",
  "shaders/upstream/ArtCNN_C4F32.glsl": "f773bce6cf5fe7e5e5d599a695edd40df5cd7a20c3d08c4d164d07591d5bead3",
  "shaders/upstream/ArtCNN_C4F32_DN.glsl": "6b51a6f7d75826c9492c3f78b5e60acffa24a71928e2d47c4a329423922a143c",
  "shaders/upstream/ArtCNN_C4F32_DS.glsl": "a04c9cba6fbb8e6db9239d61848390208aedf8e348ef116e12174c803d22077e",
  "shaders/FSRCNNX_x2_56-16-4-1.glsl": "34cd5d0087ebb6ae5f9bff2578382205457da53baa364d52de8021d6925b7fd6",
  "model/FSRCNNX_x2_16-0-4-1.wgsl": "ff7e001ee85d139eb704be1981cd306e8d515145ca06fc3da26a12f9e78d4755",
  "model/FSRCNNX_x2_16-0-4-1.passes.json": "6e58179e009ee8d599019359465566d4525acd65c5669519f0ca63398186df1d",
  "model/FSRCNNX_x2_56-16-4-1.wgsl": "267ba203867483a467c535fd03c36c62ff9428116111d4d258dc5c295ef8e0d7",
  "model/FSRCNNX_x2_56-16-4-1.passes.json": "57395ac668b4cbebea69938a9089c9bea0029ce785f7cc6dad239c4be31d43e7",
  "model/FSRCNNX_x3_16-0-4-1.wgsl": "7df8eaae1c6f50bfd2b494d403cce8e1638c7408e0b92362b174cb72fdf816fb",
  "model/FSRCNNX_x3_16-0-4-1.passes.json": "b96ed9241b9e5303d17eb05c13c923f2173465046317d44b4d95cf627fecb80b",
  "model/FSRCNNX_x4_16-0-4-1.wgsl": "3be5b66c0d87f222f2b192ceb4c4e66b6b5f6759e00872ab3b70a542c3ee38e3",
  "model/FSRCNNX_x4_16-0-4-1.passes.json": "25a5cdacc30aaef84b738bc64981afdaf6a17aabff5e68456a0afa4961f804ea",
  "model/ArtCNN_C4F32.artcnn.wgsl": "af2b1911fe4ec1f77354b71d5aa6796c93b4d53eb73cd693b59af7e8cfb9d654",
  "model/ArtCNN_C4F32.artcnn.json": "4ab29b29a6121e0fa3d3880b890bedabb3ea1f49356ef46704ad1770b143077a",
  "model/ArtCNN_C4F32_DN.artcnn.wgsl": "f204b33d52614e87bc9d8d31ba43822ad3bad1ff75da8d425ca6fbd90a2032a9",
  "model/ArtCNN_C4F32_DN.artcnn.json": "b5911c707c83462c79dcf954bcaf422efd2d6b42efd4d08228361ab8ea52fe79",
  "model/ArtCNN_C4F32_DS.artcnn.wgsl": "f6de86466a0ae261c178f53d72d2cb79032ade94b8ec452f51fa1315b93be3c5",
  "model/ArtCNN_C4F32_DS.artcnn.json": "f98bbd5e834cbfb2ed66ba07865889f76466279e356bfbd62c33df73e95b30cb",
  "fsrcnnx-ssimds.js": "3674dca07245f02025e00e9aabf1e37eae67566f673e29fa5edd637c444f0da1",
  "fsrcnnx-sharpen.js": "a00868c13ec291c116e52a1d1fe9a069eb7a7ba037e665abc202710d72ac1ab7",
  "fsrcnnx-deband.js": "05495befe6af578baa3fb84b69983a0dddc943d60b249411cc81c7eca1bbbbaf",
};

for (const [path, expected] of Object.entries(pinnedArtifacts)) {
  try {
    const actual = createHash("sha256").update(readFileSync(resolve(root, path))).digest("hex");
    if (actual !== expected) errors.push(`${path}: SHA-256 ${actual}, expected ${expected}`);
  } catch (error) {
    errors.push(`${path}: cannot verify pinned artifact (${error.message})`);
  }
}

for (const name of readdirSync(modelDir).filter((file) => /\.(?:passes|artcnn)\.json$/.test(file)).sort()) {
  const manifest = JSON.parse(readFileSync(resolve(modelDir, name), "utf8"));
  if (!Array.isArray(manifest.passes) || manifest.passes.length === 0) {
    errors.push(`${name}: missing passes`);
    continue;
  }

  const available = new Set(["LUMA"]);
  manifest.passes.forEach((pass, index) => {
    if (pass.index !== index) errors.push(`${name}: pass ${index} has index ${pass.index}`);
    if (!Array.isArray(pass.binds) || pass.binds.length === 0) errors.push(`${name}: pass ${index} has no inputs`);
    for (const bind of pass.binds || []) {
      if (!available.has(bind)) errors.push(`${name}: pass ${index} binds unavailable ${bind}`);
    }
    if (pass.save) {
      // FSRCNNX intentionally reuses logical names across mapping bands. A later
      // pass replaces the prior texture in the runtime's logical resource map.
      available.add(pass.save);
    }
  });

  const wgslName = name.replace(/\.passes\.json$/, ".wgsl").replace(/\.artcnn\.json$/, ".artcnn.wgsl");
  const wgsl = readFileSync(resolve(modelDir, wgslName), "utf8");
  const entries = [...wgsl.matchAll(/@compute\s+@workgroup_size[\s\S]{0,180}?fn\s+(\w+)/g)];
  if (entries.length !== manifest.passes.length) {
    errors.push(`${name}: ${manifest.passes.length} passes but ${entries.length} WGSL compute entries`);
  }
}

const neuralManifest = JSON.parse(readFileSync(resolve(modelDir, "neural", "manifest.json"), "utf8"));
const neuralKeys = new Set();
for (const entry of neuralManifest) {
  if (!entry.key || neuralKeys.has(entry.key)) errors.push(`neural manifest: invalid/duplicate key ${entry.key}`);
  neuralKeys.add(entry.key);
  if (!Number.isInteger(entry.scale) || entry.scale < 1) errors.push(`neural manifest: invalid scale for ${entry.key}`);
  const file = resolve(modelDir, "neural", entry.file || "");
  try {
    if (!statSync(file).isFile()) throw new Error();
  } catch {
    errors.push(`neural manifest: missing model ${entry.file}`);
  }
}

if (errors.length) {
  for (const error of errors) console.error(error);
  process.exit(1);
}
console.log(`Model manifests: ok (${basename(modelDir)})`);
